services:
  db:
    image: postgis/postgis:15-3.3
    container_name: nearest_partner_db
    restart: always
    environment:
      POSTGRES_USER: user_name
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: partner_database
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: